# Generated by Django 3.0.7 on 2020-12-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201216_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='is_features',
            new_name='is_featured',
        ),
    ]
